package ir.dinal.storehub.ui

import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import ir.dinal.storehub.data.*
import ir.dinal.storehub.worker.WorkerScheduler
import kotlinx.coroutines.launch

@Composable fun SyncScreen(nav:NavHostController){val ctx=LocalContext.current;val store=remember{LocalStore.get(ctx)};val prefs=remember{WooPrefs(ctx)};val scope=rememberCoroutineScope();var busy by remember{mutableStateOf(false)};var page by remember{mutableIntStateOf(0)};var message by remember{mutableStateOf("این سینک مستقیم از گوشی به WooCommerce وصل می‌شود و فقط اطلاعات کاتالوگ، قیمت، SKU، دسته و عکس را می‌گیرد. موجودی مغازه و دپو تغییر نمی‌کند.")}
    Shell(nav,"سینک مستقیم ووکامرس"){Text("سایت: ${prefs.baseUrl.ifBlank{"هنوز تنظیم نشده"}}");if(page>0)Text("در حال دریافت صفحه $page...");Busy(busy);Text(message);Button({scope.launch{busy=true;page=0;runCatching{store.syncWoo{p->page=p}}.onSuccess{message="افزوده: ${it.added} | بروزشده: ${it.updated} | خطا: ${it.failed}\n${it.message}"}.onFailure{message=it.message?:"خطا"};busy=false}},enabled=!busy&&prefs.hasKey()&&prefs.hasSecret()&&prefs.baseUrl.isNotBlank(),modifier=Modifier.fillMaxWidth()){Text(if(busy)"در حال سینک..." else "شروع سینک")}}
}

@Composable fun SettingsScreen(nav:NavHostController){val ctx=LocalContext.current;val prefs=remember{WooPrefs(ctx)};val store=remember{LocalStore.get(ctx)};val backup=remember{BackupManager(ctx)};val scope=rememberCoroutineScope();var base by remember{mutableStateOf(prefs.baseUrl)};var version by remember{mutableStateOf(prefs.apiVersion)};var key by remember{mutableStateOf("")};var secret by remember{mutableStateOf("")};var auto by remember{mutableStateOf(prefs.autoSync)};var minutes by remember{mutableStateOf(prefs.autoSyncMinutes.toString())};var queryAuth by remember{mutableStateOf(prefs.queryStringAuth)};var busy by remember{mutableStateOf(false)};var message by remember{mutableStateOf<String?>(null)}
    fun candidate()=WooSettings(baseUrl=base.trim().trimEnd('/'),apiVersion=version.trim().trim('/').ifBlank{"wc/v3"},consumerKey=key.ifBlank{prefs.consumerKey()},consumerSecret=secret.ifBlank{prefs.consumerSecret()},autoSync=auto,autoSyncMinutes=minutes.toIntOrNull()?:60,queryStringAuth=queryAuth)
    val exportLauncher=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/json")){uri->if(uri!=null)scope.launch{busy=true;runCatching{backup.exportTo(uri)}.onSuccess{message="فایل پشتیبان با موفقیت ذخیره شد."}.onFailure{message=it.message};busy=false}}
    val importLauncher=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null)scope.launch{busy=true;runCatching{backup.importFrom(uri)}.onSuccess{base=prefs.baseUrl;version=prefs.apiVersion;auto=prefs.autoSync;minutes=prefs.autoSyncMinutes.toString();queryAuth=prefs.queryStringAuth;message="بازیابی انجام شد. برای امنیت، Consumer Key/Secret را دوباره وارد کن."}.onFailure{message=it.message};busy=false}}
    Shell(nav,"تنظیمات و بکاپ"){
        Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){
            Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("اتصال مستقیم به WooCommerce",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("هیچ بک‌اند یا سروری بین اپ و ووکامرس وجود ندارد. کلیدها فقط روی همین گوشی و با Android Keystore رمزگذاری می‌شوند.");OutlinedTextField(base,{base=it},label={Text("آدرس سایت — حتماً HTTPS")},placeholder={Text("https://example.com")},modifier=Modifier.fillMaxWidth());OutlinedTextField(version,{version=it},label={Text("نسخه API")},placeholder={Text("wc/v3")},modifier=Modifier.fillMaxWidth());Text("سرویس: ${base.trimEnd('/')}/wp-json/${version.trim('/')}/products",style=MaterialTheme.typography.bodySmall);OutlinedTextField(key,{key=it},label={Text(if(prefs.hasKey())"Consumer Key — قبلاً ذخیره شده" else "Consumer Key")},placeholder={Text(if(prefs.hasKey())"برای حفظ کلید فعلی خالی بگذار" else "ck_...")},modifier=Modifier.fillMaxWidth());OutlinedTextField(secret,{secret=it},label={Text(if(prefs.hasSecret())"Consumer Secret — قبلاً ذخیره شده" else "Consumer Secret")},placeholder={Text(if(prefs.hasSecret())"برای حفظ Secret فعلی خالی بگذار" else "cs_...")},modifier=Modifier.fillMaxWidth());Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text("Query-string auth فقط در صورت مشکل هاست");Text("پیش‌فرض خاموش؛ Basic Auth روی HTTPS امن‌تر است.",style=MaterialTheme.typography.bodySmall)};Switch(queryAuth,{queryAuth=it})};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("سینک خودکار");Switch(auto,{auto=it})};if(auto)OutlinedTextField(minutes,{minutes=it},label={Text("فاصله سینک (حداقل 15 دقیقه)")},modifier=Modifier.fillMaxWidth());Busy(busy);message?.let{Text(it)};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({val s=candidate();if(!s.baseUrl.startsWith("https://")){message="آدرس باید با https:// شروع شود.";return@Button};prefs.baseUrl=s.baseUrl;prefs.apiVersion=s.apiVersion;prefs.autoSync=s.autoSync;prefs.autoSyncMinutes=s.autoSyncMinutes;prefs.queryStringAuth=s.queryStringAuth;if(key.isNotBlank())prefs.setConsumerKey(key);if(secret.isNotBlank())prefs.setConsumerSecret(secret);key="";secret="";WorkerScheduler.scheduleWoo(ctx);Toast.makeText(ctx,"تنظیمات ذخیره شد",Toast.LENGTH_SHORT).show();message="تنظیمات فقط روی همین گوشی ذخیره شد."},modifier=Modifier.weight(1f)){Text("ذخیره")};OutlinedButton({scope.launch{busy=true;runCatching{store.testWoo(candidate())}.onSuccess{message=it.message}.onFailure{message=it.message};busy=false}},enabled=!busy,modifier=Modifier.weight(1f)){Text("تست اتصال")}};TextButton({prefs.clearCredentials();key="";secret="";message="کلیدهای ووکامرس از گوشی حذف شدند."}){Text("حذف کلیدهای ذخیره‌شده")}}
            }
            Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("پشتیبان‌گیری محلی",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("بکاپ شامل کالاها، دو انبار، فروش‌ها، مرجوعی‌ها، خریدها، چک‌ها و قرارهاست. Consumer Secret عمداً داخل فایل بکاپ قرار نمی‌گیرد.");Button({exportLauncher.launch("storehub-backup-${todayPersian().replace('/','-')}.json")},enabled=!busy,modifier=Modifier.fillMaxWidth()){Text("گرفتن فایل بکاپ")};OutlinedButton({importLauncher.launch(arrayOf("application/json","text/plain"))},enabled=!busy,modifier=Modifier.fillMaxWidth()){Text("بازیابی از فایل بکاپ")};Text("هشدار: بازیابی، اطلاعات فعلی StoreHub روی گوشی را با فایل انتخاب‌شده جایگزین می‌کند.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.error)} }
            Text("StoreHub V6 Local — بدون VPS، بدون SQL Server، بدون پنل وب. دیتابیس اصلی Room داخل همین گوشی است.",style=MaterialTheme.typography.bodySmall)
        }
    }
}
